### ISSUE TITLE
Different collection in homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Stephanie-Goldman-Speed#2]
Preview: https://7wmro9bx1z0cq1o1-51680837823.shopifypreview.com/
![image](https://user-images.githubusercontent.com/97726944/169788066-115fa610-08db-4a62-b2e7-3c63aa543ffc.png)

Live: https://lucettecollection.com/
![image](https://user-images.githubusercontent.com/97726944/169787735-62cbb65b-6d92-45f6-b07d-1232139f78a2.png)

**Comment by Shoaibans** [comment]
@Ataurrahman-khan @devabulabbas Now the 1st two collection images are not coming in the first load.
Video: https://www.awesomescreenshot.com/video/9102919?key=7304ba1e8fe665ebd1beec94582054b9

**Comment by Ataurrahman-khan** [comment]
https://www.awesomescreenshot.com/video/9105092?key=eaf286e93f3377819b12757c341e5eab

**Comment by Shoaibans** [comment]
> https://www.awesomescreenshot.com/video/9105092?key=eaf286e93f3377819b12757c341e5eab

@Ataurrahman-khan @devabulabbas pls check the issue in incognito/private window.

**Comment by devabulabbas** [comment]
Resolved @Shoaibans
