### ISSUE TITLE
Different image in homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Stephanie-Goldman-Speed#3]
Preview: https://7wmro9bx1z0cq1o1-51680837823.shopifypreview.com/
![image](https://user-images.githubusercontent.com/97726944/169788216-fdf151c2-19f2-485f-8925-4f01f29a0256.png)

Live: https://lucettecollection.com/
![image](https://user-images.githubusercontent.com/97726944/169788268-b42551b4-c536-406e-a24d-f5abb6449ba6.png)

**Comment by Ataurrahman-khan** [comment]
resolved
