### ISSUE TITLE
Missing images from blog page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Stephanie-Goldman-Speed#5]
Preview: https://7wmro9bx1z0cq1o1-51680837823.shopifypreview.com/blogs/lanai/monday-moodboard-coastal-cool-resort-wear
Video: https://www.awesomescreenshot.com/video/9043221?key=7b605ba5a0ef8039cc8c2ed667523a39

Live: https://lucettecollection.com/blogs/lanai/monday-moodboard-coastal-cool-resort-wear

**Comment by Shoaibans** [comment]
@Ataurrahman-khan @devabulabbas Now, sometimes the banner/image in header is not coming in first load blog page.
Preview: https://7r77mm3kcfrhz2pp-51680837823.shopifypreview.com/blogs/lanai/resort-wear
![image](https://user-images.githubusercontent.com/97726944/170415314-3f254bff-b5e3-42b2-9f4f-5950b8401d06.png)

Live: https://lucettecollection.com/blogs/lanai/resort-wear
![image](https://user-images.githubusercontent.com/97726944/170415352-89ce571c-b56f-42db-8837-0e79ba8f2038.png)

**Comment by devabulabbas** [comment]
@Shoaibans loading Properly checked

**Comment by Shoaibans** [comment]
Resolved
![image](https://user-images.githubusercontent.com/97726944/170449729-ec0379ef-575b-418f-8b54-a0ec89cf25d2.png)
