### ISSUE TITLE
Missing afterpay app from product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Stephanie-Goldman-Speed#6]
Preview: https://7wmro9bx1z0cq1o1-51680837823.shopifypreview.com/products/iridescent-slip-on-bangle-gold-and-honey?pr_prod_strat=collection_fallback&pr_rec_id=8f5ea0e2e&pr_rec_pid=6309498192063&pr_ref_pid=6575722594495&pr_seq=uniform&variant=39457050165439
![image](https://user-images.githubusercontent.com/97726944/169796768-569901e6-8391-4600-a5ac-56500efaf959.png)

Live: https://lucettecollection.com/products/iridescent-slip-on-bangle-gold-and-honey?pr_prod_strat=collection_fallback&pr_rec_id=18debe6c1&pr_rec_pid=6309498192063&pr_ref_pid=6146589294783&pr_seq=uniform&variant=39457050165439
![image](https://user-images.githubusercontent.com/97726944/169797010-863aae0a-c76e-4d9e-9e33-2639c6a55814.png)

**Comment by devabulabbas** [comment]
@Shoaibans 
![image](https://user-images.githubusercontent.com/100209490/170423729-48ceeba5-df07-4f76-9128-f234e983683b.png)

**Comment by Shoaibans** [comment]
@devabulabbas pls check the issue in incognito tab
![image](https://user-images.githubusercontent.com/97726944/170448446-595a72af-69ac-4cae-ab9a-d6e741627113.png)

**Comment by devabulabbas** [comment]
![image](https://user-images.githubusercontent.com/100209490/170684942-a59fafbb-a0f8-4800-8bd5-d39edd2028da.png)
On making theme live it wil come automatically @Shoaibans

**Comment by Shoaibans** [comment]
Will check on live
