### ISSUE TITLE
Missing buy now button from product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Stephanie-Goldman-Speed#7]
Preview: https://7wmro9bx1z0cq1o1-51680837823.shopifypreview.com/products/stella-hat-naturel-x-noir?_pos=1&_sid=244b815d9&_ss=r&_fid=89c5a993a
![image](https://user-images.githubusercontent.com/97726944/169798211-73caafc2-d5af-49d0-af97-b05716199332.png)

Live: https://lucettecollection.com/products/stella-hat-naturel-x-noir?_pos=1&_sid=244b815d9&_ss=r&_fid=89c5a993a
![image](https://user-images.githubusercontent.com/97726944/169798455-e2f8033e-7e2a-444f-a51d-abe6854f3c84.png)

**Comment by Ataurrahman-khan** [comment]
Resolved

**Comment by Shoaibans** [comment]
Resolved
Preview: 
![image](https://user-images.githubusercontent.com/97726944/170449331-4ab5d885-072f-481a-afd7-bc98c106ba81.png)
Live:
![image](https://user-images.githubusercontent.com/97726944/170449422-d793fd05-4c0b-4ebe-ac84-25600ff1fab0.png)
